[package]
name = "rodinizer2"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]
edition = "2018"

[dependencies]
rand = { version = "0.7", features = ["small_rng"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "rodinizer"
harness = false
